# Generated by Django 4.0.4 on 2022-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
