# Generated by Django 4.0.4 on 2022-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
